const days=['Sign Up & Registration','Company Name Selection','Logo Design','Website Theme Selection','Social Media Creations','GST Registration','Product Knowledge Training','Order Management Training','Marketing Channels Training','Branding Training','Digital Marketing Training','Enquiry Handling SOPs','Process Templates','Bank Account Opening','Marketing Kit E-version','Website Backend Training','Marketing Plan','Training Evaluation','Feedback','Business Live'];
document.querySelector('#timeline').innerHTML=days.map((d,i)=>`<div class="day" style="transition-delay:${i*0.035}s"><b>DAY ${String(i+1).padStart(2,'0')}</b><span>${d}</span></div>`).join('');
const header=document.querySelector('header');const menu=document.querySelector('.menu');
menu.addEventListener('click',()=>header.classList.toggle('open'));document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>header.classList.remove('open')));
const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},{threshold:.08});
document.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));
document.querySelectorAll('.reveal-stagger').forEach(el=>{const c=el.children;Array.from(c).forEach((ch,i)=>{ch.style.transitionDelay=`${i*0.05}s`});observer.observe(el)});
const bar=document.getElementById('progressBar');window.addEventListener('scroll',()=>{const y=window.scrollY;const h=document.documentElement.scrollHeight-window.innerHeight;bar.style.width=Math.min(y/h*100,100)+'%';if(y>80)header.classList.add('scrolled');else header.classList.remove('scrolled')},{passive:true});
document.querySelectorAll('a[href^="#"]').forEach(a=>{a.addEventListener('click',e=>{const id=a.getAttribute('href');if(id==='#')return;const target=document.querySelector(id);if(target){e.preventDefault();const offset=header.offsetHeight+16;const top=target.getBoundingClientRect().top+window.scrollY-offset;window.scrollTo({top,behavior:'smooth'})}})})
